### ISSUE TITLE
Feature Request! RTE

### ISSUE THREAD

**Issue by dantarion** [lullius/MoveTool#1]
This is something I would love to see implemented that I had personally implemented for SF4 on 360.

The idea is that we can dump the currently loaded BAC/BCM files from memory, process them into JSON, and the monitor the JSON files. Whenever they change, we can rebuild them back into BAC/BCM, allocate memory in the SF5 process, and then update the data pointers to point to our newly modified files.

This would help immensely in terms of figuring out what the rest of the parameters do! The only issue we would really have is finding out which pointers to touch when making the swap, and ensuring that we don't crash the game by leaving the character in a strange state.

I think with some work we could make this app work as part of this repo, and I am willing to do my part to make it happen? What do you think?

**Comment by lullius** [comment]
I had originally planned something like that. I don't play the game and made this thing just for fun, but I got bored with it and needed a break. Anyway, I made a tool that makes editing the moves in real-time possible. I didn't test it much at all so expect crashes. Instructions in the README. I compiled and uploaded it to the "Releases"-section. Please excuse the GUI. I can't do those. It basically works like this:

You put original uasset-files in a folder called "Originals".
The tool will scan the memory and look for anything in that folder.
If you have modded files you need to put those in that folder for the tool to find them as well.
If you leave the folder empty the tool will find the BCMs/BACs in memory, but can't name them.
The tool will ask for a json-file so it can replace what's in memory originally.
To do that is allocates new memory and converts the json to uasset with movelib and then writes the BAC/BCM to the new space.
Anything that points to the original BAC/BCM is redirected to the new address (probably buggy).
Whenever the tool detects a change in the json it re-converts it and re-loads it into memory.
Each BCM/BAC that is loaded in the game can be "linked" to its own json-file, so you can edit more files at once.

As I mentioned, this is probably really buggy. I only tested a few files with Ryu and Ken, but it seems to work. There's no need to re-enter a match, just modify the json-file. The game seems to tolerate quite a lot of messing about with the BACs/BCMs. I recommend clicking the "Restore Game" button before exiting a match. The game will probably crash if you don't. And also if you do, I guess, but less chance of it happening I think.

Feel free to fork this repo if you want to help getting rid of bugs.

**Comment by dantarion** [comment]
Awesome! I have a little miniproject coming up and this will allow me to easily add SF5 to it
